(defun to_javascript_array (x)
    (if (and (listp x) (not (null x)))
        (let ((javascript_array "["))
            (dolist (xelem (butlast x) javascript_array)
                (setq javascript_array  (concatenate 'string javascript_array (write-to-string (coerce xelem 'single-float)) ","))
            )
            (setf javascript_array (concatenate 'string javascript_array (write-to-string (coerce (car (last x)) 'single-float)) "]"))
        )  
    )
)